### ISSUE TITLE
Vertical Extent min and max values show as mandatory but are optional

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#10]
https://www.agi.org.uk/agi-groups/standards-committee/uk-gemini/40-gemini/1062-gemini-datasets-and-data-series#16

**Comment by archaeogeek** [comment]
Can't seem to get this to work- it seems to be set as optional in both schemas/gmd/extent.xsd and in loc/eng/labels.xml

**Comment by josegar74** [comment]
According to the specification seem the `gmd:verticalElement` is optional, but if present the values are mandatory.

In the editor I see the element can be removed, maybe an option so it's more clear to users would be to remove it from the template and add a button `Add vertical extent` to add the element if not present?

**Comment by archaeogeek** [comment]
Yes that sounds like a good idea. I think I see how to do this so I will try it and come back to you if I get stuck.

Jo

**Comment by archaeogeek** [comment]
Kind of working, but still no visible CRS element shown in either view, see https://github.com/AstunTechnology/iso19139.gemini23/issues/3

**Comment by archaeogeek** [comment]
Closing as this is now working for both datasets and services and we're dealing with the CRS issue in https://github.com/AstunTechnology/iso19139.gemini23/issues/3
