### ISSUE TITLE
update-fixed-info should remove uuidrefs

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#106]
If these are found in the `gmd:onLine` element, they cause the canonical formatter page not to display, which then triggers an error in google search console

**Comment by archaeogeek** [comment]
We should at least strip out empty ones

**Comment by archaeogeek** [comment]
In GeoNetwork 4.2.x the canonical view is http://localhost:8080/geonetwork/srv/api/records/{identifier}?language=all (get from the sitemap at http://localhost:8080/geonetwork/srv/api/sitemap?format=html)

**Comment by archaeogeek** [comment]
@alexarobu I think you should be able to test this by adding a lineage source and checking in xml view in the editor whether it adds a `uuidref=""` attribute.

**Comment by alexarobu** [comment]
All tested- works as expected
