### ISSUE TITLE
Add srv:operateson to update-fixed-info.xsl

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#112]
See https://github.com/AGIuk/Schematron/issues/7#issuecomment-768886931 for explanation

**Comment by archaeogeek** [comment]
See https://github.com/AGIuk/Schematron/issues/7#issuecomment-768886931 and test on a Gemini 2.3 service record. Create one from the services template, then check that the srv:operatesOn element is empty. I think it should be expanded in the editor to an empty element that you can fill in, but if you leave it empty it should remove it and correctly validate.

**Comment by archaeogeek** [comment]
@alexarobu could you pull an update and re-test this? If you remove the `srv:operatesOn` elements from (eg) the sample service record from Gemini 2.3, in normal editing view you should see the following:
![Screenshot from 2023-02-21 11-28-27](https://user-images.githubusercontent.com/1544849/220333293-2162a75b-0f70-4344-a2e0-93f124ea0b6b.png)
When you validate or save and close the record you should see "`=== Removing Empty Coupled Resource ===`" in the logs. When you view the record as raw xml (not in the editing view) then you should see that there is no `srv:operatesOn` element.
Similarly if you validate a record with a completed `srv:operatesOn` element, the logs should say "`=== Retaining Non-Empty Coupled Resource ===`"

**Comment by alexarobu** [comment]
All works as expected after the last commit.
