### ISSUE TITLE
GEMINI Conformity/ ISO DQ_ConformanceResult: can only see what resource conforms to when editing

### ISSUE THREAD

**Issue by PeterParslow** [AstunTechnology/iso19139.gemini23#116]
**Describe the bug**
GEMINI / INSPIRE records use DQ_ConformanceResult to state conformance (or non conformance) to a cited specification. The preferred encoding is to use gmx:Anchor within the DQ_ConformanceResult/CI_Citation/title element. This element is only visible on the "quality" tab of the "Full view" Display mode, or when editing. Unless editing, the gmx:Anchor encoding isn't displayed, so the user can't see what specification the resource is actually claiming to conform to (or not).

**To Reproduce**
View a GEMINI record in "Full view"; choose the Quality tab. For example, at https://geo6catalogue.bgs.ac.uk/geonetwork/srv/eng/catalog.search#/metadata/d442b64c-c8c8-11e4-8731-1681e6b88ec1/formatters/xsl-view?root=div&view=advanced. 

**Expected behavior**
Display the title, probably within Data quality / report / citation, with some introductory text such as "title".

**Screenshots**
![image](https://user-images.githubusercontent.com/8492193/116974892-b542a080-acb6-11eb-9293-81b40af47365.png)

**Additional context**
Occurs in both the GeoNetwork / GEMINI instances I have access to (as above, and at Ordnance Survey)

**Comment by archaeogeek** [comment]
@PeterParslow I can confirm that this is not a Gemini issue per se as it occurs in other metadata profiles too. Without making changes to core geonetwork, we need a different work-around. There does seem to be one, which is to change the `fullview` formatter (in the admin console/settings/user interface tab) to a different formatter. Unfortunately there's a minor issue with this (not sure if it's a bug or an implementation error) so I will make enquiries.

**Comment by PeterParslow** [comment]
It has a vague relationship to https://github.com/geonetwork/core-geonetwork/issues/4805 - except that (from the use of the namespace prefix gcx in the comments) that issue is about the new 19115-3 schemas.

Would it be helpful (in your view) if I expanded the conversation there to encourage recognition of gmx:Anchor for the title as well as the code? (as per INSPIRE TG & therefore GEMINI). Presumably though that would only get it "fixed" in GeoNetwork for the newer schemas.

Should I instead raise a new issue? Is any work progressing on the ISO 19139 schema GeoNetwork core implementation? (Some INSPIRE issues do seem to have been fixed this year)

**Comment by archaeogeek** [comment]
@PeterParslow good catch. It doesn't seem to be an applicable approach for schemas based on iso19139 unfortunately. I do have another avenue to investigate, which is that the EA profile behaves differently, but it is older code and therefore not a quick compare and contrast. I have also asked the question on the developer mailing list but have had no response yet.

**Comment by archaeogeek** [comment]
We've improved this in the 4.2.x branch:
![Screenshot from 2023-02-23 17-56-24](https://user-images.githubusercontent.com/1544849/220990327-78c9746b-236a-4fac-a500-4d1ba1ae8d3b.png)
@PeterParslow would you like it back-ported?

**Comment by PeterParslow** [comment]
Depends on what is happening with the idea to upgrade/migrate our instance to GeoNetwork 4.2 to bring us back in line with other Astun instances (& fix a couple of other things)

**Comment by archaeogeek** [comment]
I'll close this for now then- it can be backported relatively easily. Fixed by https://github.com/AstunTechnology/iso19139.gemini23/commit/ab59b295d7049bd1c46b023d2ef8ee395f49ab05
