### ISSUE TITLE
missing voice element from contact metadata invalidates records in the editor board

### ISSUE THREAD

**Issue by alexarobu** [AstunTechnology/iso19139.gemini23#128]
If there is no "Voice" box under the Point of Contact section the record appears invalid in the Editor board.

![image](https://user-images.githubusercontent.com/36423106/202755048-3304c5a0-2f06-4a37-9b3a-6d5202b6e840.png)

The problem seems to be introduced when the "Voice" box is deleted from the record, making the XML incorrectly display as:

```
<gmd:phone>
 <gmd:CI_Telephone/>
</gmd:phone>
```

The correct way of filling this through the XML (so that the record validates in the Editor board) seems to be:

```
<gmd:phone>
 <gmd:CI_Telephone>
  <gmd:voice gco:nilReason="missing">
   <gco:CharacterString/>
  </gmd:voice>
 </gmd:CI_Telephone>
</gmd:phone>
```

This is not immediately obvious in the UI through the error messages. The record validates ok in the editing view and the error it shows in the Editor board is confusingly making the user look at a different section of the record (Resource Identifier code) which has nothing to do with the actual issue:

![image](https://user-images.githubusercontent.com/36423106/202758284-3a71ad88-66c6-4767-8ad0-7241ae2e2d0c.png)

There is no easy way of adding the missing section back through the UI; the only way I could find was to edit the actual XML code to add the "Voice" lines and then re-import the record in the catalogue.

**Comment by archaeogeek** [comment]
Closed by https://github.com/AstunTechnology/iso19139.gemini23/commit/a0df9838d857095a26794a044c21741f15656019
