### ISSUE TITLE
Improve editor guidance for the distribution format version

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#133]
This should highlight the fact that if the version is unknown you should choose "unknown" from the dropdown (in fact it should be added to https://github.com/AstunTechnology/iso19139.gemini23/blob/4.2.x/src/main/plugin/iso19139.gemini23/loc/eng/labels.xml#L1600 as well). If possible it should also point out that you should not fill in the nilreason *and* the version box.

**Comment by archaeogeek** [comment]
Acgtually @alexarobu all we need to do is improve the guidance!

**Comment by alexarobu** [comment]
resolved by commit [b6b870](https://github.com/AstunTechnology/iso19139.gemini23/commit/7beccabd9e2200f8f888b2dea4e02bebd2b6b870)
