### ISSUE TITLE
Improve guidance on end temporal extent

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#135]
The correct way to indicate the end temporal extent being "present day" or similar is as follows:
![Screenshot from 2023-02-22 13-38-43](https://user-images.githubusercontent.com/1544849/220635996-ec541d49-3d31-4dd1-b177-2a76bd7948e3.png)

In other words, you activate the "more details", then choose "indeterminate position" and then choose the option from the dropdown list. The guidance needs to be updated to reflect this.

**Comment by alexarobu** [comment]
resolved by commit [06709b3](https://github.com/AstunTechnology/iso19139.gemini23/commit/06709b360e879181ff9b4f0ef45faf90fccf80d5)
