### ISSUE TITLE
fix invalid <gmd:pass> element in the templates

### ISSUE THREAD

**Issue by alexarobu** [AstunTechnology/iso19139.gemini23#142]
This seems to affect all 3 templates (i.e. dataset, series and service)

![image](https://user-images.githubusercontent.com/36423106/226981911-90b63cc5-de06-4260-b502-9c4c1f08c898.png)

The Degree needs to be expanded into a boolean, not a characterString

**Comment by archaeogeek** [comment]
Closed by https://github.com/AstunTechnology/iso19139.gemini23/commit/9ef8251e072dd122ca49c680ede8c18e77b3d9e6
