### ISSUE TITLE
Review dcat/rdf output

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#146]
See https://github.com/geonetwork/core-geonetwork/issues/7332

**Comment by PeterParslow** [comment]
@archaeogeek : this issue has resurfaced in the UK CDDO-led government metadata work, where I'm presenting the geospatial metadata approach as something they can learn from. The fact that Geonetwork provides invalid RDF has rather distracted at least Alasdair (who raised the issue against Geonetwork) from the examples of dct:spatial

As I understand his comment, RDF does not allow something to be both a link and a literal, so the dct:license is incorrect. You can see the discussion embedded in the issue I linked to last week, ending with a suggestion of:

```
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

<https://osmetadata.astuntechnology.com/geonetwork/srv/resources/datasets/OS+1:50+000+Scale+Colour+Raster>
    a dcat:Dataset ;
    dct:license <http://www.ordnancesurvey.co.uk/oswebsite/business/licences/index.html> .

<http://www.ordnancesurvey.co.uk/oswebsite/business/licences/index.html>
    rdfs:label "Use limitation dependent upon licence" ;
    rdfs:comment "Licences and agreements explained" .
```
    
    With the remaining problem that the OS web page may not match the DCAT definition of a license.

**Comment by archaeogeek** [comment]
@PeterParslow happy to work on this- I created this issue because afaik the problem is not with GeoNetwork per se but with my implementation in Gemini. Hopefully I can look at it next week

**Comment by archaeogeek** [comment]
@PeterParslow the option to download/export as rdf in GeoNetwork 4.2.x is deprecated, but you can use the new ogc-api endpoint to request a record in dcat format. When this is topped and tailed with an `<rdf:RDF>` element and run through the validator that Alastair suggests we use, it returns a valid result. Are you happy to report that back to the CDDO? If so, I'll close this. 

I'll also get in touch with Alastair separately as the EA external URL that he used for his example is no longer valid.

**Comment by PeterParslow** [comment]
That's good, and I would be happy to report it. . Could you send me a sample of that RDF DCAT? (Any record will do).

**Comment by archaeogeek** [comment]
[rdf-validator-test-record.zip](https://github.com/AstunTechnology/iso19139.gemini23/files/13515525/rdf-validator-test-record.zip)

I've just sent that to Alastair too. Note it was picked entirely at random so I can't guarantee it's a totally valid Gemini record!

**Comment by PeterParslow** [comment]
I've put it here for the CDDO team to look at: https://github.com/co-cddo/ukgov-metadata-exchange-model/issues/1#issuecomment-1834161636

**Comment by archaeogeek** [comment]
Great- are you happy for me to close this in favour of raising anything specific that comes up as a new issue?

**Comment by PeterParslow** [comment]
Sure
