### ISSUE TITLE
ESRI:REST protocol encoding

### ISSUE THREAD

**Issue by alexarobu** [AstunTechnology/iso19139.gemini23#150]
@archaeogeek it seems that there is a slight issue with the encoding of the ESRI REST protocol; I created a new branch and pushed an updated list that seems to work better in GeoNetwork - allowing you to add ESRI REST layers to the map straight from record view (https://github.com/AstunTechnology/iso19139.gemini23/commit/60d60c5f1219afc0aa1970c026f5382e62fddff6)

See https://spatialdata.gov.scot/geonetwork/srv/eng/catalog.search#/metadata/13396739-7602-4428-85fd-95a5d7e208a1 vs the updated https://sandpit-gn.astuntechnology.com/geonetwork/srv/eng/catalog.search#/metadata/13396739-7602-4428-85fd-95a5d7e208a1

But do you know if the recommended options here in the "Distribution formats" also come from somewhere within Gemini?
![image](https://github.com/user-attachments/assets/8afdd0bf-afb5-4936-a701-966c00cdb69f)

Ideally, the ESRI REST one at the top would match the updated value to say "ESRI:REST" instead of "WWW:DOWNLOAD:ESRI REST", but I couldn't find it anywhere to update it, so I wonder if it's actually Gemini or GeoNetwork :frowning_face:

**Comment by archaeogeek** [comment]
I think this comes from labels.xml in the schema? See  https://github.com/geonetwork/core-geonetwork/blob/cfcd829615063742849fbe1bde11261098dd3713/schemas/iso19139/src/main/plugin/iso19139/loc/eng/labels.xml#L2270 for example

**Comment by alexarobu** [comment]
@archaeogeek yeah, so the updated list here should be better (I took it from the same place you linked) - are you OK if I open a PR so we can include it in the 4.2.x branch of Gemini?

I am still not too sure where the other bit in that list comes from though (the top part, under "Distribution formats")

**Comment by archaeogeek** [comment]
Should also be in labels as well, or in config-editor.xml? Happy for a PR
