### ISSUE TITLE
spatial data service type needs a suggestions list

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#18]
https://www.agi.org.uk/agi-groups/standards-committee/uk-gemini/40-gemini/1063-gemini-services#26

**Comment by archaeogeek** [comment]
I've tried to replicate the process in 0b9a5c7a87ec4018fec0286ed2a625b3e112fb57 to box up the spatial data service type but it's not working- same problem as in https://github.com/AstunTechnology/iso19139.gemini23/issues/14

**Comment by josegar74** [comment]
Committed in `services` branch, please try it. Should be rendered like:

![servicetype-suggestions](https://user-images.githubusercontent.com/1695003/63578516-f2253d00-c590-11e9-9e84-c3bb15658d21.png)

**Comment by archaeogeek** [comment]
Awesome, thankyou!
