### ISSUE TITLE
3.6.x: layout-custom-fields sections for gml:duration and topic categories don't work

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#19]
` Error at xsl:with-param on line 25 column 100 of layout-custom-fields.xsl:
  XPST0017: XPath syntax error at char 54 on line 25 in {...ype($editorConfig, name(), ...}:
    Cannot find a matching 3-argument function named
  {http://geonetwork-opensource.org/xsl/functions/metadata}getFieldType()
Error at xsl:call-template on line 190 column 46 of layout-custom-fields.xsl:
  XTSE0680: Parameter directive is not declared in the called template
Error at xsl:call-template on line 237 column 50 of layout-custom-fields.xsl:
  XTSE0680: Parameter directive is not declared in the called template`

Temporarily fixed by commenting out sections of layout-custom-fields.xsl but not a long term solution

**Comment by josegar74** [comment]
Updated the code for 3.6.x branch, please double check and close it if looks fine for you also.

**Comment by archaeogeek** [comment]
Happy this now works, thanks
