### ISSUE TITLE
Conformity is now mandatory so needs to be present in default view 

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#2]
A button to add a conformity block should show in default view when it's missing
https://www.agi.org.uk/agi-groups/standards-committee/uk-gemini/40-gemini/1062-gemini-datasets-and-data-series#41

**Comment by josegar74** [comment]
@archaeogeek, some questions:

- In the specification there're examples for titles using `CharacterString` and `Anchor`. It's preferred the last, but in the editor it's not that simple to change from 1 to other. Should he button add the element as an `Anchor`?

- The element `gmd:pass` by default is displayed with  a checkbox, that doesn't allow to select `unknown` value. An option is to define the conformity sections using a template field like in the INSPIRE view: https://github.com/geonetwork/core-geonetwork/blob/master/schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml#L1606, or other option can be backport https://github.com/geonetwork/core-geonetwork/pull/3569 so can be used this widget without using a template field.

----

Something that can be useful is to add a selection field that uses the directories feature with the preconfigured reports, so can be selected and added. The user can change them once added to the metadata. See screenshot:

![quality-reports](https://user-images.githubusercontent.com/1695003/59659098-b4c5bd00-91a5-11e9-8628-e0a2df5ba451.png)


![quality-reports-directory](https://user-images.githubusercontent.com/1695003/59659163-dfb01100-91a5-11e9-81b1-ed1ce191e22d.png)

**Comment by archaeogeek** [comment]
Hi Jose,

Yes please add the title element as an anchor, as the guidance recommends that. With the `gmd:pass` element, my understanding is that the nilreason should be unknown, so I think, unless I have misunderstood you, that backporting https://github.com/geonetwork/core-geonetwork/pull/3569 might be the best option?

I like the idea of allowing people to choose from preconfigured entries here as well.

Thanks

Jo

**Comment by archaeogeek** [comment]
@josegar74 I'm working on the conformity element and have asked the Gemini 2.3 working group for guidance on the problem gmd:pass being displayed as a boolean and how best to depict the "unknown".There's also a similar problem with the explanation element (see https://www.agi.org.uk/agi-groups/standards-committee/uk-gemini/40-gemini/1062-gemini-datasets-and-data-series#41), which is allegedly mandatory, but can be empty. I am struggling to think of a good way to display this.

I'd definitely like to look at backporting https://github.com/geonetwork/core-geonetwork/pull/3569. From what I can see from the commits, it looks like it should be fairly easy to do? Should it be done in iso19139 or just in Gemini 2.3? Can it be extended to text elements like gmd:explanation as well?

Regarding the list of preconfigured entries- are these already available somewhere that I could use or would I need to build them from scratch?

Thanks

Jo

**Comment by archaeogeek** [comment]
@josegar74 I've assigned this to me for the moment as I've been having a look at the way this element is implemented in the INSPIRE view and I think it works well, so I'm going to try adding the template code to the default view. I have also found examples of several of the INSPIRE conformance reports so I can start to build some directory entries for those. If I need more help I'll come back to you.

**Comment by archaeogeek** [comment]
Needs work. Probably not defining sections correctly in config-editor- see attached xml for a complex example
[export-full-1568051839414.zip](https://github.com/AstunTechnology/iso19139.gemini23/files/3591903/export-full-1568051839414.zip)

**Comment by archaeogeek** [comment]
@josegar74 I'm struggling with this. I want to replicate the fields and sections that appear as standard for Data Quality but with a template for conformance result so I can have radio buttons for degree (see below for the standard view).

![Screenshot from 2019-09-10 15-54-26](https://user-images.githubusercontent.com/1544849/64624951-52b2d780-d3e3-11e9-9d6b-2d417c12d6cd.png)

Here's a complex example as a snippet: It has two levels of scope (dataset and attribute) and for the dataset scope multiple reports.

```
<gmd:dataQualityInfo>
      <gmd:DQ_DataQuality>
         <gmd:scope>
            <gmd:DQ_Scope>
               <gmd:level>
                  <gmd:MD_ScopeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#MD_ScopeCode"
                                    codeListValue="dataset"/>
               </gmd:level>
            </gmd:DQ_Scope>
         </gmd:scope>
         <gmd:report>
            <gmd:DQ_DomainConsistency>
               <gmd:result>
                  <gmd:DQ_ConformanceResult>
                     <gmd:specification>
                        <gmd:CI_Citation>
                           <gmd:title>
                              <gco:CharacterString>INSPIRE Implementing rules laying down technical arrangements for the interoperability and harmonisation of Geology</gco:CharacterString>
                           </gmd:title>
                           <gmd:date>
                              <gmd:CI_Date>
                                 <gmd:date>
                                    <gco:Date>2011</gco:Date>
                                 </gmd:date>
                                 <gmd:dateType>
                                    <gmd:CI_DateTypeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#CI_DateTypeCode"
                                                         codeListValue="publication"/>
                                 </gmd:dateType>
                              </gmd:CI_Date>
                           </gmd:date>
                        </gmd:CI_Citation>
                     </gmd:specification>
                     <gmd:explanation>
                        <gco:CharacterString>See the referenced specification</gco:CharacterString>
                     </gmd:explanation>
                     <gmd:pass>
                        <gco:Boolean>false</gco:Boolean>
                     </gmd:pass>
                  </gmd:DQ_ConformanceResult>
               </gmd:result>
            </gmd:DQ_DomainConsistency>
         </gmd:report>
         <gmd:report>
            <gmd:DQ_DomainConsistency>
               <gmd:result>
                  <gmd:DQ_ConformanceResult>
                     <gmd:specification>
                        <gmd:CI_Citation>
                           <gmd:title>
                              <gmx:Anchor xlink:href="http://data.europa.eu/eli/reg/2010/1089">Commission Regulation (EU) No 1089/2010 of 23 November 2010 implementing Directive 2007/2/EC of the European Parliament and of the Council as regards interoperability of spatial data sets and services</gmx:Anchor>
                           </gmd:title>
                           <gmd:date>
                              <gmd:CI_Date>
                                 <gmd:date>
                                    <gco:Date>2010-12-08</gco:Date>
                                 </gmd:date>
                                 <gmd:dateType>
                                    <gmd:CI_DateTypeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#CI_DateTypeCode"
                                                         codeListValue="publication"/>
                                 </gmd:dateType>
                              </gmd:CI_Date>
                           </gmd:date>
                        </gmd:CI_Citation>
                     </gmd:specification>
                     <!-- Explanation is a required element but can be empty -->
              <gmd:explanation gco:nilReason="inapplicable"/>
                     <!-- 
                     <gmd:explanation>
                        <gco:CharacterString>TG Requirement C.22: metadata/2.0/req/common/conformity-degree states that: Each gmd:report/gmd:DQ_DomainConsistency/gmd:result/gmd:DQ_ConformanceResult element containing a specification citation described in Requirement C.21 shall also include the degree of declared conformity against this specification using gmd:pass property with gco:Boolean value of "true" for a conformant</gco:CharacterString>
                     </gmd:explanation>
                      -->
              <!-- If the conformance failed then 
                     <gmd:pass>
                        <gco:Boolean>false</gco:Boolean>
                     </gmd:pass> -->
              <!-- If not tested then -->
              <gmd:pass gco:nilReason="unknown"/>
                  </gmd:DQ_ConformanceResult>
               </gmd:result>
            </gmd:DQ_DomainConsistency>
         </gmd:report>
         <gmd:report>
            <gmd:DQ_TopologicalConsistency>
               <gmd:nameOfMeasure>
                  <gco:CharacterString>Number of faulty point-curve connections</gco:CharacterString>
               </gmd:nameOfMeasure>
               <gmd:evaluationMethodType>
                  <gmd:DQ_EvaluationMethodTypeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#DQ_EvaluationMethodTypeCode"
                                                   codeListValue="indirect"/>
               </gmd:evaluationMethodType>
               <gmd:evaluationMethodDescription>
                  <gco:CharacterString>A point-curve connection exists where different curves touch...</gco:CharacterString>
               </gmd:evaluationMethodDescription>
               <gmd:dateTime/>
               <gmd:result>
                  <gmd:DQ_QuantitativeResult>
                     <gmd:valueUnit xlink:href="http://www.opengis.net/def/uom/OGC/1.0/unity"/>
                     <gmd:value>
                        <gco:Record xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:integer">12</gco:Record>
                     </gmd:value>
                  </gmd:DQ_QuantitativeResult>
               </gmd:result>
            </gmd:DQ_TopologicalConsistency>
         </gmd:report>
         <gmd:report>
            <gmd:DQ_TopologicalConsistency>
               <gmd:result>
                  <gmd:DQ_ConformanceResult>
                     <gmd:specification>
                        <gmd:CI_Citation>
                           <gmd:title>
                              <gco:CharacterString>INSPIRE Data Specifications - Base Models - Generic Network Model</gco:CharacterString>
                           </gmd:title>
                           <gmd:date>
                              <gmd:CI_Date>
                                 <gmd:date>
                                    <gco:Date>2013-04-05</gco:Date>
                                 </gmd:date>
                                 <gmd:dateType>
                        <!-- The code list value shall always be publication -->
                        <gmd:CI_DateTypeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#CI_DateTypeCode"
                                                         codeListValue="publication"/>
                                 </gmd:dateType>
                              </gmd:CI_Date>
                           </gmd:date>
                        </gmd:CI_Citation>
                     </gmd:specification>
                     <!-- An explanation must be provided-->
              <gmd:explanation>
                        <gco:CharacterString>[Some statement on topological consistency]</gco:CharacterString>
                     </gmd:explanation>
                     <gmd:pass>
                <!-- The value shall always be false to indicate that the data does not assure the centerline topology for the network -->
                <gco:Boolean>false</gco:Boolean>
                     </gmd:pass>
                  </gmd:DQ_ConformanceResult>
               </gmd:result>
            </gmd:DQ_TopologicalConsistency>
         </gmd:report>
         <gmd:report>
            <gmd:DQ_DomainConsistency>
               <gmd:measureDescription gco:nilReason="unknown"/>
               <gmd:result>
                  <gmd:DQ_QuantitativeResult>
                     <gmd:valueUnit/>
                     <gmd:value/>
                  </gmd:DQ_QuantitativeResult>
               </gmd:result>
            </gmd:DQ_DomainConsistency>
         </gmd:report>
         <gmd:lineage>
            <gmd:LI_Lineage>
               <gmd:statement>
                  <gco:CharacterString>The dataset has been compiled continuously since the year 1918 (statistics from 1913).</gco:CharacterString>
               </gmd:statement>
               <gmd:processStep>
                  <gmd:LI_ProcessStep>
                     <gmd:description/>
                  </gmd:LI_ProcessStep>
               </gmd:processStep>
               <gmd:source>
                  <gmd:LI_Source/>
               </gmd:source>
            </gmd:LI_Lineage>
         </gmd:lineage>
      </gmd:DQ_DataQuality>
  </gmd:dataQualityInfo>
   <gmd:dataQualityInfo>
      <gmd:DQ_DataQuality>
         <gmd:scope>
            <gmd:DQ_Scope>
               <gmd:level>
                  <gmd:MD_ScopeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#MD_ScopeCode"
                                    codeListValue="attribute"/>
               </gmd:level>
            </gmd:DQ_Scope>
         </gmd:scope>
      </gmd:DQ_DataQuality>
  </gmd:dataQualityInfo>
```

However when I start to break down the gmd:DataQualityInfo element as a section with fields in (rather than using xpath) then it groups together the elements incorrectly, so all the gmd:scope elements appear together, then all the gmd:report elements. This is wrong- gmd:DataQualityInfo is the repeating element when there are multiple scopes (and then within each gmd:DataQualityInfo element there can be multiple reports).

I've tried many combinations of sections and fields, and the template snippet from the inspire view, but while I can get the template to display correctly, I can't figure out the grouping.

Could you take a look? There's a separate branch for conformity. I'll keep working on it at the moment.

Thanks!

**Comment by josegar74** [comment]
@archaeogeek apologies for the delay, I'm going to check and will provide feedback

**Comment by josegar74** [comment]
@archaeogeek Checking your comments, with current code will not work using template fields as they handle all the elements matching the xpath, so will be displayed the different elements from each `gmd:dataQualityInfo` together.

If the rendering with xpath is ok, but just missing the radio buttons for the `gmd:pass`, please check this PR: https://github.com/geonetwork/core-geonetwork/pull/3569, can be backported to 3.4.x branch the JS code and should work.

Check the comments about the inflate / update-fixed-info process for the elements using this directive, in this case will be `gmd:pass` and let me know if want me to integrate it to your 3.4.x branch

**Comment by archaeogeek** [comment]
@josegar74 sorry, I completely failed to spot your earlier comment about this. If you could backport https://github.com/geonetwork/core-geonetwork/pull/3569 into the conformity branch for me, that would be great. I've seen the comments about inflate-metadata and update-fixed-info and I think I'm OK with those. Thanks!

**Comment by josegar74** [comment]
@archaeogeek I have backported to 3.4.x, but most of the changes are required in 3.4.x branch / iso19139. 

I'll check to do a PR with these changes to 3.4.x so you can cherry pick them in your 3.4.x branch and will commit the specific stuff for GEMINI 2.3 in the `conformity` branch.

**Comment by josegar74** [comment]
I have committed the changes. 

Require  to integrate this PR in your custom GeoNetwork 3.4.x branch: https://github.com/geonetwork/core-geonetwork/pull/4039

**Comment by archaeogeek** [comment]
@josegar74 I've cherrypicked https://github.com/geonetwork/core-geonetwork/pull/4039 and am up to date with https://github.com/AstunTechnology/iso19139.gemini23/commit/5c628644e87dc3744e6756ed17286bee442b1497 but I'm getting a syntax error:

```
Error at xsl:with-param on line 25 column 100 of layout-custom-fields.xsl:
  XPST0017: XPath syntax error at char 54 on line 25 in {...ype($editorConfig, name(), ...}:
    Cannot find a matching 3-argument function named
  {http://geonetwork-opensource.org/xsl/functions/metadata}getFieldType()
```
This is odd because I think it's line 27 that has that code in it, but I'm sure I've got everything up to date. My version is up and running on http://21f94328.ngrok.io/geonetwork if it would help for you to take a look?

Thanks

**Comment by archaeogeek** [comment]
@josegar74 I eventually got this problem resolved, I had a conflict in one of the other schemas when I applied https://github.com/geonetwork/core-geonetwork/pull/4039 and didn't realise. This is working fine thanks, so I'll close it now.
