### ISSUE TITLE
Vertical extent needs a CRS element

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#3]
Vertical extent is optional so this only needs to be in advanced view, but the CRS is a component and it doesn't display, though it is added in the xml as an empty element. Note this works (up to a point) in Gemini 2.2 though I'd like to see it much easier to use than it currently is, if possible.
https://www.agi.org.uk/agi-groups/standards-committee/uk-gemini/40-gemini/1062-gemini-datasets-and-data-series#16

**Comment by josegar74** [comment]
Fixed in https://github.com/AstunTechnology/iso19139.gemini23/commit/26961820b7eea809dd248166b957d715efad7006

Missed to add the issue reference in the commit, apologies

**Comment by archaeogeek** [comment]
@josegar74 The basic problem is fixed, but it's really hard to add the information to match the examples in the guidelines. To fix this would the best approach be to add a button to the default view and then create a template? Ideally I'd like to set the default value of the CRS and use the picker to allow people to search if they want a different one. If this is the best approach I'd like to try and implement it myself so I know how in future!

**Comment by josegar74** [comment]
@archaeogeek there're some options:

1) If the list is quite fixed and not very prone to change, I would use a dropdown action, you can see an example in the INSPIRE view for reference systems:

https://github.com/geonetwork/core-geonetwork/blob/master/schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml#L727

2) A more dynamic approach is to use the directories feature, where you can add snippets with the different value:

```
<gmd:verticalCRS xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href='http://www.opengis.net/def/crs/EPSG/0/5701'/>
```

And adding to `config-editor.xml`:

```
<for name="gmd:verticalCRS" addDirective="data-gn-directory-entry-selector">
      <directiveAttributes
        data-template-add-action="true"
        data-search-action="true"
        data-popup-action="true"
        data-template-type="verticalCRS"
        data-insert-modes=""
        data-variables=""/>
    </for>
```

This requires some additional work in https://github.com/geonetwork/core-geonetwork/blob/master/schemas/iso19139/src/main/plugin/iso19139/index-fields/index-subtemplate.xsl to index the content properly and also some testing.

I would go for option 1) unless doesn't cover the requirements.

**Comment by archaeogeek** [comment]
@josegar74 I think in default view I will be wanting a single option for the vertical CRS, so option 1 is good. That would cover the first encoding example in https://www.agi.org.uk/agi-groups/standards-committee/uk-gemini/40-gemini/1062-gemini-datasets-and-data-series#16. However if I use that approach, and people are editing metadata where the second encoding example is used, I'm not sure how that will display? Will that just be a case of adding it as a flat mode exception?

**Comment by archaeogeek** [comment]
Hi Jose,

Could you take a look at d26d1b069c1680ed0f332dbfa2ae7d3822cb682e and help me understand why it's not working? What it's supposed to do (and seems to do just fine in Oxygen editor) is test for whether a vertical min and max extent are included, but no vertical CRS. In that case, it should add a vertical CRS with the default value. If there's no vertical min and max extent included, it shouldn't add anything. In geonetwork 3.4 it doesn't seem to work at all...

Thanks

Jo

**Comment by josegar74** [comment]
I have added some logging in the `inflate-metadata.xsl` and removed from a metadata the vertical CRS.

I get this:

```
hasTimePeriodElement: true
hasTimeInstantElement: false
hasBboxElement: true
hasVerticalCRSElement: false
hasVerticalExtentMin: true
hasVerticalExtentMax: true
```

That causes to enter in this condition:

https://github.com/AstunTechnology/iso19139.gemini23/blob/services/src/main/plugin/iso19139.gemini23/inflate-metadata.xsl#L164-L166

Instead of this one that I guess is what is expected:

https://github.com/AstunTechnology/iso19139.gemini23/blob/services/src/main/plugin/iso19139.gemini23/inflate-metadata.xsl#L101

This condition doesn't seem fine:

`<xsl:when test="(not($hasTimePeriodElement) and not($hasTimeInstantElement)) or not($hasBboxElement)">`

With the previous values is `false`:

```
hasTimePeriodElement: true
hasTimeInstantElement: false
hasBboxElement: true
```

I'm checking to change the check using also `hasVerticalCRSElement`:

`<xsl:when test="(not($hasTimePeriodElement) and not($hasTimeInstantElement)) or not($hasBboxElement) or not($hasVerticalCRSElement)">`

, but found some issues in the snippet adding the `gmd:verticalElement`, checking to fix them and will provide the changes. 

@archaeogeek please confirm in which branch to commit this fix.

**Comment by josegar74** [comment]
I have update the code to the following and seem working fine now:

```
  <xsl:template match="gmd:MD_DataIdentification">
...
        <xsl:when test="(not($hasTimePeriodElement) and not($hasTimeInstantElement)) or not($hasBboxElement) or not($hasVerticalCRSElement)">
          <!-- Add  temporal extent or bbox elements (if missing) to the first gmd:extent -->
          <xsl:for-each select="gmd:extent">
            <xsl:copy>
              <xsl:copy-of select="@*" />

              <xsl:choose>
                <xsl:when test="position() = 1">
                  <xsl:for-each select="gmd:EX_Extent">
                    <xsl:copy>
                      <xsl:copy-of select="@*" />

                      <xsl:apply-templates select="gmd:description" />

                      <xsl:choose>
                        <xsl:when test="not($hasBboxElement)">
                          <xsl:call-template name="addBboxElement" />
                        </xsl:when>
                        <xsl:otherwise>
                          <xsl:apply-templates select="gmd:geographicElement" />
                        </xsl:otherwise>
                      </xsl:choose>

                      <xsl:choose>
                        <xsl:when test="not($hasTimePeriodElement) and not($hasTimeInstantElement)">
                          <xsl:call-template name="addTimePeriodElement" />
                        </xsl:when>
                        <xsl:otherwise>
                          <xsl:apply-templates select="gmd:temporalElement" />
                        </xsl:otherwise>
                      </xsl:choose>

                      <xsl:choose>
                        <!-- add vertical CRS if it's missing-->
                        <!-- but only if vertical min and max are present -->
                        <xsl:when test="($hasVerticalExtentMin and $hasVerticalExtentMax) and not($hasVerticalCRSElement)">
                          <xsl:for-each select="gmd:verticalElement">
                            <xsl:copy>
                              <xsl:copy-of select="@*" />

                              <xsl:choose>
                                <xsl:when test="position() = 1">
                                  <xsl:for-each select="gmd:EX_VerticalExtent">
                                    <xsl:copy>
                                      <xsl:copy-of select="@*" />

                                      <xsl:apply-templates select="gmd:minimumValue" />
                                      <xsl:apply-templates select="gmd:maximumValue" />
                                      <xsl:message>Got vertical extent but no CRS</xsl:message>
                                      <xsl:call-template name="addVerticalCRSElement" />
                                    </xsl:copy>
                                  </xsl:for-each>
                                </xsl:when>

                                <xsl:otherwise>
                                  <xsl:apply-templates select="*"/>
                                </xsl:otherwise>
                              </xsl:choose>

                            </xsl:copy>
                          </xsl:for-each>
                        </xsl:when>
                        <xsl:otherwise>
                          <xsl:apply-templates select="gmd:verticalElement" />
                        </xsl:otherwise>
                      </xsl:choose>

                    </xsl:copy>

                  </xsl:for-each>
                </xsl:when>

                <xsl:otherwise>
                  <xsl:apply-templates select="*"/>
                </xsl:otherwise>
              </xsl:choose>
            </xsl:copy>
          </xsl:for-each>
        </xsl:when>
...
</xsl:template>

...

  <xsl:template name="addVerticalCRSElement">
       <gmd:verticalCRS xlink:href='http://www.opengis.net/def/crs/EPSG/0/5701'/>
  </xsl:template>
```

But checking http://www.datypic.com/sc/niem21/e-gmd_EX_VerticalExtent.html, `gmd:verticalCRS ` is mandatory, not sure why needs to be inflated. Just to confirm should not be checked if maybe empty (no `xlink:href` or empty value) instead of not present?

**Comment by archaeogeek** [comment]
Hi Jose,

I've tried to apply your change above, but I'm getting a problem- the vertical CRS is added (I can see it in the xml) but it doesn't show properly in the editing view.

This is what I have in the xml:
`
<gmd:verticalElement>
                  <gmd:EX_VerticalExtent>
                     <gmd:minimumValue>
                        <gco:Real xmlns:gco="http://www.isotc211.org/2005/gco">5</gco:Real>
                     </gmd:minimumValue>
                     <gmd:maximumValue>
                        <gco:Real xmlns:gco="http://www.isotc211.org/2005/gco">45</gco:Real>
                     </gmd:maximumValue>
                     <gmd:verticalCRS xmlns:gml="http://www.opengis.net/gml/3.2"
                                      xmlns:gco="http://www.isotc211.org/2005/gco"
                                      xmlns:xlink="http://www.w3.org/1999/xlink"
                                      xlink:href="http://www.opengis.net/def/crs/EPSG/0/5701"/>
                  </gmd:EX_VerticalExtent>
               </gmd:verticalElement>
`

but this screenshot shows how it displays in the editing view (default) once I have saved:
![Screenshot from 2019-09-02 18-01-39](https://user-images.githubusercontent.com/1544849/64127937-c59ccc80-cdab-11e9-9a9a-1f4dbb91b55d.png)

So... I think I must have something wrong with my code. I am happy for you to commit your changes to the 3.4.x branch and then we can discuss if more needs to be done.

Thanks

Jo

**Comment by josegar74** [comment]
I think the problem is that by default no template handling elements with empty content and only `xlink:href` , checking to implement a custom template

**Comment by josegar74** [comment]
Please check last commit. For the case 1 allows to edit the value:

![vertical-crs](https://user-images.githubusercontent.com/1695003/64254584-fb62c200-cf1f-11e9-91c5-261a38c20521.PNG)


It's also ready to show a boxed section for case 2, although that requires additional work as the children elements from `gml` namesapce are not rendered properly.

Can you confirm if case 2 is required?

Also for case 1, helper list with suggested values is not working with the `xlink:href` attribute, but not sure if required. If so, please provide the list of suggestions and will work to support the suggestions.

**Comment by archaeogeek** [comment]
@josegar74 I think this works fine, though I'm not sure what you mean by case 2? A suggestions list would be good- this link shows all the UK vertical projection systems: https://epsg.io/?q=United%20Kingdom%20kind%3AVERTCRS but if you start it for me I can populate it.

**Comment by josegar74** [comment]
Ok, I'll check to get it working the suggestion list with this element.

About `case 2` I mean from https://www.agi.org.uk/agi-groups/standards-committee/uk-gemini/40-gemini/1062-gemini-datasets-and-data-series#16 the 2on example that instead of  `xlink:href` contains `gml` elements to define the CRS.

**Comment by josegar74** [comment]
@archaeogeek I have done some changes in the helper directive to support this element, the code was not ready for empty elements with an attribute.

![vertical-crs-suggestions](https://user-images.githubusercontent.com/1695003/64421936-17db3780-d0a3-11e9-9ed5-a9a1e7b7add2.PNG)


Please check if this looks as expected. 


It requires some javascript changes outside of the schema. I plan to make a PR, but please try the changes at your end with `3.4.x` branch first:

1) In `labels.xml` add the helper info, updating the label for the element `gmd:verticalCRS`:

```
  <element name="gmd:verticalCRS">
    <label>Vertical CRS</label>
    <description>Provides information about the origin from which the maximum and minimum elevation
      values are measured
    </description>
    <helper relAtt="xlink:href">
      <option value="http://www.opengis.net/def/crs/EPSG/0/5701">ODN height (United Kingdom) - EPSG:5701</option>
      <option value="http://www.opengis.net/def/crs/EPSG/0/7707">ODN (Offshore) height (United Kingdom) - EPSG:7707</option>
      <option value="http://www.opengis.net/def/crs/EPSG/0/5730">EVRF2000 height (Europe) - EPSG:5730</option>
      <option value="http://www.opengis.net/def/crs/EPSG/0/5621">EVRF2000 height (Europe) - EPSG:5621</option>
      <option value="http://www.opengis.net/def/crs/EPSG/0/5732">Belfast height - EPSG:5732</option>
      <option value="http://www.opengis.net/def/crs/EPSG/0/5741">Fair Isle height - EPSG:5741</option>
      <option value="http://www.opengis.net/def/crs/EPSG/0/5748">Flannan Isles height - EPSG:5748</option>
      <option value="http://www.opengis.net/def/crs/EPSG/0/5743">Foula height - EPSG:5743</option>
      <option value="http://www.opengis.net/def/crs/EPSG/0/5731">Malin Head height - EPSG:5731</option>
      <option value="http://www.opengis.net/def/crs/EPSG/0/5745">North Rona height - EPSG:5745</option>
      <option value="http://www.opengis.net/def/crs/EPSG/0/5742">Lerwick height - EPSG:5742</option>
      <option value="http://www.opengis.net/def/crs/EPSG/0/5740">ODN Orkney height - EPSG:5740</option>
      <option value="http://www.opengis.net/def/crs/EPSG/0/7962">Poolbeg height (m) - EPSG:7962</option>
      <option value="http://www.opengis.net/def/crs/EPSG/0/5754">Poolbeg height (ft(Br36)) - EPSG:5754</option>
      <option value="http://www.opengis.net/def/crs/EPSG/0/5749">St Marys height - EPSG:5749</option>
      <option value="http://www.opengis.net/def/crs/EPSG/0/5747">St Kilda height - EPSG:5747</option>
      <option value="http://www.opengis.net/def/crs/EPSG/0/5746">Stornoway height - EPSG:5746</option>
      <option value="http://www.opengis.net/def/crs/EPSG/0/5744">Sule Skerry height - EPSG:5744</option>
    </helper>
  </element>
```

2) Change this snippet:

https://github.com/geonetwork/core-geonetwork/blob/5d1f32ca761e91b4768dc1396271c54908e98e24/web-ui/src/main/resources/catalog/components/edit/editorhelper/EditorHelperDirective.js#L59-L64

```
          // Retrieve the target field by name (general case)
          // or by id (template mode field).
          var field = document.gnEditor[scope.ref] || $('#' + scope.ref).get(O),
              relatedAttributeField = document.gnEditor[scope.relatedAttr],
              relatedElementField = document.gnEditor[scope.relatedElement],
              initialValue = field.value;
```

With the following:

```
          // Retrieve the target field by name (general case)
          // or by id (template mode field).
          var field = document.gnEditor[scope.ref];
          if (field == undefined && ($('#' + scope.ref).length > 0)) {
            field = $('#' + scope.ref).get(O);
          }

          // For suggestions in attributes of empty elements where is only rendered the attribute, like
          //    <gmd:verticalCRS xlink:href="http://www.opengis.net/def/crs/EPSG/0/5702"/>
          // Use the field for the attribute.
          if ((field == undefined) && (angular.isDefined(scope.relatedAttr)) && (scope.relatedAttr != '')) {
            field = document.gnEditor[scope.relatedAttr.replace(":", "COLON")];
          }

          var relatedAttributeField = document.gnEditor[scope.relatedAttr],
              relatedElementField = document.gnEditor[scope.relatedElement],
              initialValue = field.value;
```

Please make sure to cleanup the JS&CSS cache.

**Comment by archaeogeek** [comment]
@josegar74 I'm not seeing any difference when I apply these changes. I am in a chrome incognito window, and have cleared all the caches, and I'm in debug mode. I have ngrok working at the moment if you want to see my local copy: http://edaf5753.ngrok.io/geonetwork

**Comment by archaeogeek** [comment]
@josegar74 this seems to be fixed in my version today so I'll mark as closed thanks.

**Comment by josegar74** [comment]
@archaeogeek  Ok, I prepared an instance locally also so you could test as for me was working.

Have you committed the JS code in a custom branch? I'll check to make a PR to `master` with the change.

**Comment by archaeogeek** [comment]
@josegar74 no it's just in the 3.4.x branch, sorry
