### ISSUE TITLE
Spatial Data Representation Type should be boxed

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#32]
@josegar74 this one is confusing me. As far as I can see, gmd:spatialRepresentationType is set up in the same was as gmd:spatialResolution, so it should be boxed in simple view. I've even tried to add it to layout-custom-fields.xsl, copying what's been done in there for srv:serviceType but it's just not working. Could you take a look for me (in the 3.4.x branch)?

**Comment by josegar74** [comment]
@archaeogeek Testing this issue with GeoNetwork `3.4.x` branch (no code changes) and GEMINI 2.3 `3.4.x` branch I get the errors you describe in https://github.com/AstunTechnology/iso19139.gemini23/issues/38 (see details in the issue about the branches tested and steps done to get it working in that issue)

Seem the GEMINI 2.3 `3.4.x` has some changes that require https://github.com/geonetwork/core-geonetwork/pull/4039 and if not available cause the error described in #38.

In any case, I'm not going to change that in `3.4.x`, will just check to fix the boxing element.

**Comment by josegar74** [comment]
Fixed:

![spatial-representation-type-boxed](https://user-images.githubusercontent.com/1695003/65854249-65725980-e35c-11e9-927e-8ce4651678e1.png)

Please check previous comment as the GEMINI 2.3 `3.4.x` branch requires an updated GeoNetwork 3.4.x version with geonetwork/core-geonetwork#4039

For example this other code doesn't work in GeoNetwork vanilla `3.4.x` branch: 
https://github.com/AstunTechnology/iso19139.gemini23/blob/e677f32079d4cce699f907926a9c0f9305655680/src/main/plugin/iso19139.gemini23/layout/layout-custom-fields.xsl#L57

**Comment by archaeogeek** [comment]
Confirmed fixed, thanks
