### ISSUE TITLE
in full view vertical extent has an "extent type code" checkbox- why?

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#4]
what is this for?

**Comment by josegar74** [comment]
@archaeogeek I don't have that element:

![vertical-extent-full-view](https://user-images.githubusercontent.com/1695003/59585961-073da580-90e2-11e9-978a-b61033bf1b79.png)

Please check to provide a sample metadata that displays it.

**Comment by archaeogeek** [comment]
I've found the example that shows this, but my bad it's not the vertical extent it's the `gmd:EX_GeographicDescription` element (eg https://www.agi.org.uk/agi-groups/standards-committee/uk-gemini/40-gemini/1062-gemini-datasets-and-data-series#15 in the guidelines). The attached record shows it
[BGSds-example1c.zip](https://github.com/AstunTechnology/iso19139.gemini23/files/3301639/BGSds-example1c.zip). I'm not sure it matters as it's not mentioned in the guidelines. I'll close this
