### ISSUE TITLE
Conformity "not evaluated" fails validation

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#40]
In 3.8.x (not checked in 3.4.x), using the new layout for conformity, the following error shows when validating:
![Screenshot from 2019-10-09 16-57-51](https://user-images.githubusercontent.com/1544849/66498443-f6aca300-eab5-11e9-8bf0-07cc1fa7392e.png)
This is using the sample record Boundary Line from the Gemini 2.3 schema, and it occurs if you validate when the record is first opened, then also when you validate after saving the record (so presumably update-fixed-info.xsl is triggered)

**Comment by archaeogeek** [comment]
@josegar74 have you had chance to look at this?

**Comment by josegar74** [comment]
@archaeogeek I'll check tomorrow apologies for the delay

**Comment by josegar74** [comment]
@archaeogeek The validation code really needs a refactor, when you click Validate first saves the metadata and validates it, but it's validated after inflating the metadata:

https://github.com/geonetwork/core-geonetwork/blob/3.8.x/core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java#L665-L680

Then after is call again the `MetadataValidateApi`, but this code uses the report in the session from previous call (what initially is fine, but as was validated after inflate process, then has the error). This call if no report in session would use the non-inflated metadata:

https://github.com/geonetwork/core-geonetwork/blob/3.8.x/services/src/main/java/org/fao/geonet/api/records/MetadataValidateApi.java#L156-L157


I'm checking to refactor https://github.com/geonetwork/core-geonetwork/blob/3.8.x/core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java#L665-L680, to validate and then inflate, but for now getting another error:

![error](https://user-images.githubusercontent.com/1695003/67069245-c2ec1000-f17c-11e9-94f8-ae0a7dcfc3b2.png)

**Comment by josegar74** [comment]
I have done the following change to validate the metadata before inflating it, but then causes other errors in the editor as the validate method adds info to the xml that validates that is used later in the metadata editor:

![error-2](https://user-images.githubusercontent.com/1695003/67069962-0c3d5f00-f17f-11e9-9d72-c33a789d5c4a.png)


```
Element metadataXmlToValidate = (Element) metadataXml.clone();

if (Files.exists(inflateStyleSheet)) {
    // --- setup environment
    Element env = new Element("env");
    env.addContent(new Element("lang").setText(srvContext.getLanguage()));

    // add original metadata to result
    Element result = new Element("root");
    result.addContent(metadataXml);
    result.addContent(env);

    metadataXml = Xml.transform(result, inflateStyleSheet);
}

if (withEditorValidationErrors) {
    final Pair<Element, String> versionAndReport = metadataValidator.doValidate(srvContext.getUserSession(), schema, id, 
        metadataXmlToValidate, srvContext.getLanguage(), forEditing);
         version = versionAndReport.two();
         metadataXml.addContent(versionAndReport.one());
...
```

Will discuss with other developers as not sure if there's a nice solution for this case.

**Comment by archaeogeek** [comment]
@josegar74 I'm worried about the implications of this. 

* Does it mean that inflate-metadata is causing problems, or specifically using the radio buttons for conformity rather than a checkbox? 
* Is this working elsewhere? 
* Do I need to revert back to using a standard checkbox for conformity?
* Will inflate-metadata cause other problems?

**Comment by josegar74** [comment]
- Does it mean that inflate-metadata is causing problems, or specifically using the radio buttons for conformity rather than a checkbox?

It causes issues with when the value is undefined as removed the boolean element.

I think is also related to the inline errors in the metadata editor, probably in 3.4.x works fine, but need to check

- Is this working elsewhere?

Dutch SDI is using it afaik, checking as I think it works, but they are in 3.6.x.

- Do I need to revert back to using a standard checkbox for conformity?

Not for now, also if you need the undefined value should not be reverted. If there's no good solution, we can try as in INSPIRE view to use a template field, not the best probably, but if works should be fine.


- Will inflate-metadata cause other problems?

I think this is very specific as is re-added a `gco:Boolean`, in other cases, suppose it´s re-add a text field, should be fine as the user can see that is empty and fill it.

**Comment by josegar74** [comment]
@archaeogeek I've been thinking about an easy solution, but need to confirm with you.

This is the current code in the inflate process adds empty boolean so can be edited in the editor:

https://github.com/AstunTechnology/iso19139.gemini23/blob/2c90011e603dd7adbdbc2e55b8dc769078486448/src/main/plugin/iso19139.gemini23/inflate-metadata.xsl#L396-L402


But that causes the validation issue as described in previous comments, I've been thinking to fill the value, but use at the same time the `@gco:nilReason` in the parent element, like:

```
<gmd:pass gco:nilReason="missing">
  <gco:Boolean>false</gco:Boolean>
</gmd:pass>
```

This change requires some updates in the widget to handle the booleans with the 3 statuses (undefined, true, false), but with previous change should validate the xsd, and when applying the update-fixed-info process, we can convert previous snippet to the "correct" one when the value is missing, removing the `gco:Boolean`.

**Comment by archaeogeek** [comment]
@josegar74 that sounds fine to me. Do you need us to order more support time before you are able to do this?

**Comment by josegar74** [comment]
@archaeogeek I have updated the code, tested the directive and seem when `gco:nilReason`  is set, it has priority over the `gco:Boolean` value and it's working well. 

Updated the inflate process to set the value and avoid the validation issue, when saved the boolean is removed as expected in the value "Not evaluated " is selected.

Please try it at your end.

**Comment by archaeogeek** [comment]
Works fine! Hurrah! More validation issues to come, unfortunately, but I'll see if I can solve them before asking you. I'll close this issue.
