### ISSUE TITLE
Add additional schematron from ISO19139 for data.gov.uk

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#44]
See https://guidance.data.gov.uk/publish_and_manage_data/harvest_or_add_data/harvest_data/gemini/#gemini. 

We have a copy of https://github.com/alphagov/ckanext-spatial/blob/master/ckanext/spatial/validation/xml/medin/ISOTS19139A1Constraints_v1.4.sch so that's easy. 

Can you also confirm that by including https://github.com/AstunTechnology/iso19139.gemini23/tree/3.8.x/src/main/plugin/iso19139.gemini23/schema/gmx and https://github.com/AstunTechnology/iso19139.gemini23/tree/3.8.x/src/main/plugin/iso19139.gemini23/schema/srv we're also validating against them as it says in the guidance link above?

**Comment by josegar74** [comment]
I have compare the files from both schemas, the changes are mostly in formatting, except for `gml` xsd files, as the ones used in the spec (https://github.com/alphagov/ckanext-spatial/tree/master/ckanext/spatial/validation/xml/iso19139eden/gml) are for GM 3.2.1 and the version in the schema is for 3.2.0. Probably

Some differences in `srv` xsd files, but seem equivalent.

In any case I can update both folders in the schema to be sure the local files are up to date with the versions in the spec, does this sound fine?

**Comment by archaeogeek** [comment]
Yes, please do update with the ones in the specification.

**Comment by archaeogeek** [comment]
@josegar74 I've replaced the schema files with the ones from https://github.com/alphagov/ckanext-spatial/tree/master/ckanext/spatial/validation/xml/iso19139eden in https://github.com/AstunTechnology/iso19139.gemini23/commit/d8b9cde97f42ad97ce96f062cc2c1e1e0a862e9c and as far as I can tell it all still works, but other than validating records and getting the same results as before, I'm not really sure what other testing I should do? Could you check for me and close if it all looks OK?

**Comment by archaeogeek** [comment]
Closing as it doesn't seem to be making any difference to validation/testing etc
