### ISSUE TITLE
Vertical extent inflate.xsl check triggers incorrectly

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#45]
It triggers when the vertical extent element is marked as `inapplicable`, whereas it should ignore that case. See world  mineral statistics dataset from the samples.

**Comment by josegar74** [comment]
I extracted the sample from branch `3.8.x`, but there's no `inapplicable` element:

```
<gmd:verticalElement>
    <gmd:EX_VerticalExtent>
        <gmd:minimumValue gco:nilReason="missing" />
        <gmd:maximumValue gco:nilReason="missing" />
        <gmd:verticalCRS />
    </gmd:EX_VerticalExtent>
</gmd:verticalElement>
```

I guess the case to manage is the following? 

```
<gmd:verticalElement  gco:nilReason="inapplicable" />
```

How should be rendered this element in the editor? Maybe inflate it so the user can enter the `gmd:verticalCRS` as for example `<gmd:verticalCRS xlink:href='http://www.opengis.net/def/crs/EPSG/0/5701'/>` and in the update-fixed-info process if is empty assign the `inapplicable` value to `gmd:verticalElement`?

**Comment by archaeogeek** [comment]
@josegar74 I've finally managed to take another look at this- and I gave you the wrong dataset, sorry. It's BGS GeoIndex - Offshore (cultural data) data theme (OGC WxS INSPIRE). The original samples come from https://github.com/AGIGemini/Schematron/tree/master/samples, and the original version of this particular dataset is https://github.com/AGIGemini/Schematron/blob/master/samples/BGSsv-examplea1.xml. If you change the metadata standard name and version to 
```
<gmd:metadataStandardName>
      <gco:CharacterString>UK GEMINI</gco:CharacterString>
 </gmd:metadataStandardName>
 <gmd:metadataStandardVersion>
      <gco:CharacterString>2.3</gco:CharacterString>
 </gmd:metadataStandardVersion>
```

Then upload that one record into Gemini 2.3 then you can see that it converts 
`<gmd:verticalElement gco:nilReason="inapplicable"/>`
 to 
```
<gmd:verticalElement gco:nilReason="missing">
      <gco:CharacterString/>
 </gmd:verticalElement>
```

The problem I have is that I don't know how many elements might have this behaviour, in other words use `gco:nilReason="inapplicable"`. Is there a way we can handle them all rather than having to state them individually?

**Comment by josegar74** [comment]
This seem to be related to the following code in the inflate process:

https://github.com/AstunTechnology/iso19139.gemini23/blob/0166415ce2f25023435888c634290372d18c62bc/src/main/plugin/iso19139.gemini23/inflate-metadata.xsl#L404-L411


We need to exclude vertical extent and probably some other elements. For the vertical element probably need to be added additional template so the user can edit the attribute with the CRS referenced. 

Please check if any other elements that require similar management, not adding the `gco:CharacterString`. I'll check to update the rule for vertical extent.

**Comment by josegar74** [comment]
@archaeogeek committed a fix for vertical element, please try it.

**Comment by archaeogeek** [comment]
@josegar74 I can see that this fix is working how you'd expect, but I don't think it's working the way the user would expect. I think that if they specifically say that the nilreason is 'inapplicable' then they want the element to be included as is, whereas this approach removes it completely. In other words it should stay as `<gmd:verticalElement gco:nilReason="inapplicable"/>`. Is that something we can do?

**Comment by josegar74** [comment]
@archaeogeek, the code should not really remove it, see the snippet in the update fixed-info:

https://github.com/AstunTechnology/iso19139.gemini23/commit/477c8fc569b8d77a4d4298a172b060497e9b9d1c#diff-0bae21a84302cb763f177e021eb2252bR112-R128

It checks if any of the children has data: `gmd:minimumValue`, `gmd:maximumValue` or `gmd:verticalCRS`. In this case the element is copied, but if all the children are empty, should replace it with this: `<gmd:verticalElement gco:nilReason="inapplicable" />`

**Comment by archaeogeek** [comment]
OK, I'll close for now and revisit if I can reproduce
