### ISSUE TITLE
Check 3.8.x branch against GeoNetwork 3.10

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#52]
Create new branch if any changes are needed

**Comment by josegar74** [comment]
I have added the schema `3.8.x` branch to GeoNetwork `3.10.x` branch with the following steps:

```
git clone https://github.com/geonetwork/core-geonetwork.git
cd core-geonetwork
git checkout 3.10.x
git submodule update --init

# Include not merged PR
git pull https://github.com/josegar74/core-geonetwork.git improvements/inspire-conformity-directive-simple-view-2

# Add GEMINI 2.3 3.8.x branch as as submodule
./add-schema.sh iso19139.gemini23 http://github.com/metadata101/iso19139.gemini23 3.8.x

# Edit schemas\iso19115-3.2018\src\main\plugin\iso19115-3.2018\layout\layout.xsl as described in https://github.com/AstunTechnology/iso19139.gemini23#adding-manual-pr
```

The application starts up properly and metadata creation, visualisation and search looks fine.

The only bizarre stuff is about the resource locator, seem some missing values. Can you confirm if that it's the same in GeoNetwork 3.8?

<img width="936" alt="editor-review" src="https://user-images.githubusercontent.com/1695003/73842432-d949d480-481c-11ea-8855-b267a038e332.png">


Checked the PR with the `schema+plugin+change` label there're 2 for 3.10.x: 

https://github.com/geonetwork/core-geonetwork/issues?q=label%3A%22schema+plugin+change%22+is%3Aclosed

- https://github.com/geonetwork/core-geonetwork/pull/4414 - It's related to styling doesn't seem affecting the schema files.
- https://github.com/geonetwork/core-geonetwork/pull/4343 - GEMINI 2.3 delegates to iso19139 template for this change, no need to do changes to GEMINI 2.3.

For the time being, we can keep current `3.8.x` schema branch for GeoNetwork 3.10, but should be reviewed the PR that are committed to GeoNetwork 3.10.x  branch with `schema+plugin+change` label to make sure no incompatible change is added. This should ideally not happen, but in case would happen we'll have to create a related `3.10.x of the schema.

In any case, please check the previous steps and if you can do some additional checks about validation rules.

**Comment by archaeogeek** [comment]
@josegar74 which record is this with? I get it for the template for datasets but not for any of the sample records

**Comment by josegar74** [comment]
I created the record from a template indeed.

**Comment by archaeogeek** [comment]
I think that's fine then. Thanks for reviewing for me. Happy to this issue, if you're OK with reviewing PRs with the `schema+plugin+change` label for anything that might cause us problems?

**Comment by josegar74** [comment]
Sure, that's fine, I'll review the PR to 3.10.x with that label so we can check if need to setup an specific branch or not.
