### ISSUE TITLE
Validation error in Gemini 2.3 with attached file

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#54]
I'm getting an error when importing the following file [gemini22_sample.zip](https://github.com/AstunTechnology/iso19139.gemini23/files/4159981/gemini22_sample.zip) into Geonetwork 3.8, using the conversion script xml_gemini22gemini23 ([https://github.com/AstunTechnology/iso19139.gemini23/blob/3.8.x/src/main/plugin/iso19139.gemini23/convert/xml_gemini22gemini23.xsl](https://github.com/AstunTechnology/iso19139.gemini23/blob/3.8.x/src/main/plugin/iso19139.gemini23/convert/xml_gemini22gemini23.xsl)) and then validating it in the editing interface. The error is due to conformance but I can't see why it's not validating- I can't see the difference between this record and the sample Boundary Line one that passes this particular rule.

Explanation- we need a conformance report to be included now even if the dataset hasn't been validated against it, so the conversion script should add the default one for datasets and series. There are also further errors in the validation but I haven't looked at them yet so they can be ignored for now!

**Comment by josegar74** [comment]
The difference is in this word of the specification title:

- Text that is checked: `data sets`
- Text in the metadata: `datasets`

**Comment by archaeogeek** [comment]
Argh! Thanks for spotting this.
