### ISSUE TITLE
Conversion xsl need updating for Gemini 2.3

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#56]
The conversion xsl in https://github.com/AstunTechnology/iso19139.gemini23/tree/3.8.x/src/main/plugin/iso19139.gemini23/convert need checking and updating to work with Gemini 2.3. The priority are the ones for WMS and WFS in https://github.com/AstunTechnology/iso19139.gemini23/tree/3.8.x/src/main/plugin/iso19139.gemini23/convert/OGCWxSGetCapabilitiesto19119, the others are less important.

**Comment by josegar74** [comment]
I understand this is for harvesting OGC WMS/WFS servers? Do you have some servers to harvest for testing?

**Comment by archaeogeek** [comment]
@josegar74 you could try http://inspire.worcester.gov.uk/geoserver/worcester/wms?service=wms&request=getcapabilities and http://inspire.worcester.gov.uk/geoserver/worcester/wfs?service=wfs&request=getcapabilities

**Comment by josegar74** [comment]
Distribution format is by default empty, I commented it so one of the schematron validates, but another requires it. Should we add a default value?

**Comment by archaeogeek** [comment]
Could we populate it with the WMS/WFS URLs?

**Comment by josegar74** [comment]
That fields are more related to the formats provided by the WMS/WFS services. See https://www.agi.org.uk/agi-groups/standards-committee/uk-gemini/40-gemini/1042-service-metadata-instance-example

I'll check to process for WMS, the `GetMap/Format` elements, see in http://inspire.worcester.gov.uk/geoserver/worcester/wms?service=wms&request=getcapabilities

**Comment by josegar74** [comment]
I have applied some fixes for WMS / WFS, please check if anything else can be improved. 

About WFS, note that the harvester supports WFS 1.0.0 and 1.1.0 (http://inspire.worcester.gov.uk/geoserver/worcester/wfs?service=wfs&request=getcapabilities&version=1.1.0). Should be supported WFS 2.0.0?

**Comment by archaeogeek** [comment]
Thanks I will check as soon as I can. Yes, could it support WFS 2.0 as well please.

**Comment by archaeogeek** [comment]
I've applied the changes but I'm getting an error on harvesting both WMS and WFS:
```
Error at xsl:call-template on line 77 column 48 of resp-party.xsl:
  XTSE0650: No template exists named freetext
Error at xsl:call-template on line 88 column 48 of resp-party.xsl:
  XTSE0650: No template exists named freetext
```

**Comment by archaeogeek** [comment]
@josegar74 I've worked around the error above by copying the freetext template from another xsl into the resp-party.xsl and calling it "freetext2". Not ideal, but it works... I then had to update the metadata standard version from 2.2 to 2.3 in OGCWxSGetCapabilitiesLayer-to-19139.xsl. 

I then get the following validation errors after harvesting:
![Screenshot from 2020-02-18 15-36-34](https://user-images.githubusercontent.com/1544849/74750976-79afe800-5264-11ea-88da-ebb6859a6371.png)

![Screenshot from 2020-02-18 15-37-00](https://user-images.githubusercontent.com/1544849/74751008-86ccd700-5264-11ea-849c-8366198b6e9e.png)

Of these, the MI-41a and MI-41o seem the most important. In general I would suspect that existing records won't have a conformity section and we can simply add one in using the default shown in example 2 of https://www.agi.org.uk/agi-groups/standards-committee/uk-gemini/40-gemini/1062-gemini-datasets-and-data-series#41.

The legal constraints sections will need re-writing as those sections have had their encoding changed. The guidelines are https://www.agi.org.uk/agi-groups/standards-committee/uk-gemini/40-gemini/1062-gemini-datasets-and-data-series#25 and https://www.agi.org.uk/agi-groups/standards-committee/uk-gemini/40-gemini/1062-gemini-datasets-and-data-series#26 but I also had a go at adding default ones here which may need work or may be OK: https://github.com/metadata101/iso19139.gemini23/blob/3.8.x/src/main/plugin/iso19139.gemini23/convert/xml_gemini22gemini23.xsl#L60-L97

AT6 is the empty distribution format, which you have already mentioned, then SP-1c is related to the empty function in the online resource locator. I wonder if we can add those in- for WMS they are generally going to be "information" and for WFS "download"?

The WFS harvest has an additional error about coordinate reference systems:
`MI-17a (Spatial Reference System): At least one coordinate reference system used in the described dataset, dataset series, or service shall be given using gmd:referenceSystemInfo/gmd:MD_ReferenceSystem/gmd:referenceSystemIdentifier/gmd:RS_Identifier`

**Comment by josegar74** [comment]
About the conformity report, there's some code to add it from the Capabilities document to the service (if defined), but it's not the case for http://inspire.worcester.gov.uk/geoserver/worcester/wms?service=wms&request=getcapabilities

And also it's added to the service metadata.

I'll add the example 2 to layers then.

**Comment by josegar74** [comment]
@archaeogeek I'm checking about the Spatial Reference System issue (also happens with the services for WMS), but not sure about this template, seem has been changed:

https://github.com/AstunTechnology/iso19139.gemini23/blob/4cfa69cac4dc7d9d831683eced713599c5e023d3/src/main/plugin/iso19139.gemini23/convert/OGCWxSGetCapabilitiesto19119/ref-system.xsl#L11-L29 to don't use the `srs`parameter, but at least for WMS 1.3.0 can't find any `SRS` element in the capabilities document and also in WFS the element is different (`DefaultSRS`). Do you know why was changed?

**Comment by archaeogeek** [comment]
@josegar74 I think that xsl should be ignored- it was something we put in for Gemini 2.2

**Comment by josegar74** [comment]
Going to restore the original xsl.

**Comment by josegar74** [comment]
@archaeogeek please try the latest version, probably some mapping for the CRS is required, but in general validation for the harvested metadata should be better.

**Comment by archaeogeek** [comment]
@josegar74 Validation is better, but there are still some issues. Using the WMS harvester URL, then looking at Worcester - SWDP Shopping Centres I get the following problems:

AT-6 errors for:
* Conformance Result -> explanation
* Format name and version
which I think might be related to the elements with nilreasons being expanded to include an empty characterstring (https://github.com/AstunTechnology/iso19139.gemini23/issues/35)

AT-6 error for Thesaurus Alt-title (and actually no keywords when there's definitely some in the GetCapabilities result)

At-6 error for Online Resource -> description and protocol for the MetadataURL and LegendURL links

Since these are at least three separate issues, I'm going to close this one and create issues for the individual problems. If you could focus on the potential nilreason problem, I will look at the others
