### ISSUE TITLE
abstract should be moved up to below the title in default view

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#6]
Just to make it easier to see

**Comment by josegar74** [comment]
I have listed the fields from `/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation` explicitly to be able to reorder them. 

Currently are listed all to work as previous configuration to render all items available in the metadata inside `gmd:citation`. Probably is ok, as optional fields like `gmd:ISBN` are displayed only if present in the xml, but please check if maybe some of them should be removed from the default view.

**Comment by archaeogeek** [comment]
Looks good!
