### ISSUE TITLE
Validation error on constraints from ISO19139A1Const.sch

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#60]
Validating the same file as in https://github.com/AstunTechnology/iso19139.gemini23/issues/54 against ISO19139A1Const.sch gives the following error:

```
ISO19139A1_ROW7_InnerTextPattern
The 'gmd:otherConstraints' element should have a value.
```

I can see where this is triggered in the schematron file: 
https://github.com/AstunTechnology/iso19139.gemini23/blob/3.8.x/src/main/plugin/iso19139.gemini23/schematron/schematron-rules-ISOTS19139A1Const.sch#L618

Can you clarify that the rule is looking for text whereas we're supplying an anchor? The anchor is correct- see https://www.agi.org.uk/agi-groups/standards-committee/uk-gemini/40-gemini/1062-gemini-datasets-and-data-series#25 so really I need to know if the schematron needs resolving (according to the guidance for data.gov.uk this schematron is used alongside the Gemini ones). 

If this is the case then no fix is currently needed, I will need to contact the Gemini working group to get it resolved.

**Comment by josegar74** [comment]
Seem having some trouble with the child element. I updated the rule to the following:

```

**Comment by archaeogeek** [comment]
@josegar74 I think it's OK to update the code as you suggest because empty elements will be picked up by the main Gemini 2.3 schematron rule Gemini2-at6.

**Comment by archaeogeek** [comment]
@josegar74 having made that change, I think it's triggering another error. The log files tell me:
                                                                                                                                                                                    
```
Error on line 813 of schematron-rules-ISOTS19139A1Const.xsl:                                                                                                                                                               
  XPTY0004: A sequence of more than one item is not allowed as the first argument of name()                                                                                                                                
  (<gmd:otherConstraints/>, <gmd:otherConstraints/>)                                                                                                                                                                       
2020-02-18 17:09:19,539 ERROR [geonetwork.datamanager] - WARNING: schematron xslt schematron-rules-ISOTS19139A1Const failed                                                                                                
; SystemID: file:/home/jo/Git/geonetwork38/web/src/main/webapp/WEB-INF/data/config/schema_plugins/iso19139.gemini23/schematron/schematron-rules-ISOTS19139A1Const.xsl; Line#: 813; Column#: -1                             
net.sf.saxon.trans.XPathException: A sequence of more than one item is not allowed as the first argument of name() (<gmd:otherConstraints/>, <gmd:otherConstraints/>)
```
This seems to come from the converted rule above, when it's in the xsl.

**Comment by josegar74** [comment]
This issue happens in these cases with 2 `gmd:otherConstraints`:

```
<gmd:resourceConstraints>
            <gmd:MD_LegalConstraints>
               <gmd:accessConstraints>
                  <gmd:MD_RestrictionCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode"
                                          codeListValue="otherRestrictions"/>
               </gmd:accessConstraints>
               <gmd:otherConstraints>
                  <gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/INSPIRE_Directive_Article13_1e">no limitations</gmx:Anchor>
               </gmd:otherConstraints>
               <gmd:otherConstraints gco:nilReason="missing">
                   <gmx:Anchor xlink:href=""></gmx:Anchor>
               </gmd:otherConstraints>
            </gmd:MD_LegalConstraints>
         </gmd:resourceConstraints>
```

It can be fixed with `name($element[1])`, but the other checks in the rule `$element/@gco:nilReason` are not fine in can exists multiple elements.

I'm splitting the rule in 2:

- Check if exists the element.
- Check if the element content is filled or has a `@gco:nilReason``

**Comment by josegar74** [comment]
The rule to check this: `Check if exists the element`, seem already managed in other checks for `gmd:otherConstraints` and `gmd:obligation`.

I have updated the existing rule a bit and the context so it' checks only if the element content is filled or not, not the number of elements as handled in other rules. Please try the attached file to double check if I could miss anything:

[schematron-rules-ISOTS19139A1Const.sch.txt](https://github.com/AstunTechnology/iso19139.gemini23/files/4234928/schematron-rules-ISOTS19139A1Const.sch.txt)

**Comment by archaeogeek** [comment]
I think this is now working so I will commit the updated version of the file and close this
