### ISSUE TITLE
temporal extent should show when missing

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#7]
It's mandatory so needs a button to add it in default view when it's missing
https://www.agi.org.uk/agi-groups/standards-committee/uk-gemini/40-gemini/1062-gemini-datasets-and-data-series#7

**Comment by josegar74** [comment]
@archaeogeek, we can use the inflate mechanism as done for topic categories in https://github.com/AstunTechnology/iso19139.gemini23/issues/9, so when the metadata is edited the temporal extent is added if not present. 

As the element is mandatory to be present I think can be a good solution and  that way we don't need to add extra button in the editor. Let me know if sounds good.

**Comment by archaeogeek** [comment]
@josegar74 I like the way the inflate mechanism works, so would like to use that approach please

**Comment by josegar74** [comment]
Fixed, the code checks for `gml:TimePeriod` or `gml:TimeInstant` and if none of them are available adds a temporal element with `gml:TimePeriod` to the first `gmd:extent` section.

**Comment by archaeogeek** [comment]
Perfect, thanks
