### ISSUE TITLE
Validation error with World Mineral Statistics dataset

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#76]
This record: https://raw.githubusercontent.com/AGIGemini/Schematron/master/samples/BGSds-example1c.xml when imported into Geonetwork (with the metadata standard name and version changed to match Gemini 2.3) fails validation against the Gemini 2.3 schematron.

The error triggered in Geonetwork is `MI-47c: Hierarchy level name for services must have value "service"`. However, this is a dataset!

The xml snippet that is causing the problem is:
```
<gmd:hierarchyLevel>
      <gmd:MD_ScopeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/gmxCodelists.xml#MD_ScopeCode" codeListValue="dataset">dataset</gmd:MD_ScopeCode>
   </gmd:hierarchyLevel>
   <gmd:hierarchyLevelName gco:nilReason="inapplicable"/>
```
The rule in the schematron is at https://github.com/AstunTechnology/iso19139.gemini23/blob/3.8.x/src/main/plugin/iso19139.gemini23/schematron/schematron-rules-GEMINI_2.3_Schema-v1.0.sch#L966-L974 but it doesn't seem to make sense to me because for `<gmd:hierarchyLevelName gco:nilReason="inapplicable"/>` the xpath `//gmd:MD_Metadata[1]/gmd:hierarchyLevelName/*[1]` doesn't return any results?

I've tried validating in Oxygen XML, both with our version of the schematron and the one at https://github.com/AGIGemini/Schematron/blob/master/GEMINI_2.3_Schematron_Schema-v1.0.sch and the AGIGemini one validates correctly, but ours fails on https://github.com/AstunTechnology/iso19139.gemini23/blob/3.8.x/src/main/plugin/iso19139.gemini23/schematron/schematron-rules-GEMINI_2.3_Schema-v1.0.sch#L1174 which doesn't look like a failure to me.

So... is the problem with the dataset, the schematron, or Geonetwork?

**Comment by josegar74** [comment]
The problem seem the editing information is added to the metadata:

```
<gmd:hierarchyLevelName xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:geonet="http://www.fao.org/geonetwork" gco:nilReason="inapplicable">
    <geonet:element ref="9" parent="1" uuid="gmd:hierarchyLevelName_499e2ee5-dffc-49e3-b9a2-59c7f17cafdb" />
  </gmd:hierarchyLevelName>
```

Checking the rule to exclude `geonet` namespace.

**Comment by josegar74** [comment]
@archaeogeek I have applied a fix, but this check doesn't do what it's indicated in the message:

https://github.com/metadata101/iso19139.gemini23/blob/8568fc1260d1baa126a028f9459e94c97b8ae9cc/src/main/plugin/iso19139.gemini23/schematron/schematron-rules-GEMINI_2.3_Schema-v1.0.sch#L971-L972

The check just verifies that has a value, but not that should be `service`, please check in case requires to be updated also.

**Comment by archaeogeek** [comment]
Happy this is fixed- as I mentioned in https://github.com/metadata101/iso19139.gemini23/commit/8568fc1260d1baa126a028f9459e94c97b8ae9cc we should probably submit this change as a Pull Request against the AGI Gemini repository as well though
