### ISSUE TITLE
Suggestions mechanism for converting Gemini 2.2 records to Gemini 2.3 is not working

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/iso19139.gemini23#87]
I have created a schemaupgrade xsl in Gemini 2.2 https://github.com/AstunTechnology/iso19139.gemini22_GN3/blob/3.8.x/src/main/plugin/iso19139.gemini22/process/iso19139.gemini23-schemaupgrade.xsl that imports https://github.com/AstunTechnology/iso19139.gemini23/blob/3.8.x/src/main/plugin/iso19139.gemini23/convert/xml_gemini22gemini23.xsl.

This works in the API using the processes endpoint. However when applied as a suggestion for editing a Gemini 2.2 record it does not. 

Suggest.xsl is here: https://github.com/AstunTechnology/iso19139.gemini22_GN3/blob/3.8.x/src/main/plugin/iso19139.gemini22/suggest.xsl

I've tried including the xsl from `xml_gemini22gemini23.xsl` directly in `iso19139.gemini23-schemaupgrade.xsl`, and renaming `xml_gemini22gemini23.xsl` to `iso19139.gemini23-schemaupgrade.xsl` and neither make any difference.

The process displays in the suggest mechanism when editing, and appears to run, but nothing happens. The log files and browser dev tools both say the following:

```
<apiError>
<code>runtime_exception</code>
<description>
Not found:0, Not owner:0, No process found:1. is not a valid value for: Processing failed
</description>
<message>BadParameterEx</message>
</apiError>
```

The URL that is being run is http://localhost:8080/geonetwork/srv/api/records/918/processes/iso19139.gemini23-schemaupgrade?process=iso19139.gemini23-schemaupgrade&id=918 which is not the same as the one being run from the API processes endpoint (that takes the UUID rather than the ID).

It looks as if it can't find the process, which makes me think I have got something wrong with the Gemini 2.2 `iso19139.gemini23-schemaupgrade.xsl`?

**Comment by josegar74** [comment]
For some reason the backend code uses the process name from the url path , but receives it as `iso19139` instead of `iso19139.gemini23-schemaupgrade`, checking what can be causing this and why the parameter is send as url path and explicit parameter in the url.

**Comment by josegar74** [comment]
@archaeogeek it has to be with `.` in the process name, I remember some issues with other services that use parameters in url path. 

For now, going to rename the process to rename `iso19139.gemini23-schemaupgrade.xsl` to `iso19139gemini23-schemaupgrade`

**Comment by josegar74** [comment]
@archaeogeek please update Gemini 2.2, should work fine now.

https://github.com/AstunTechnology/iso19139.gemini22_GN3/commit/7e2dfc000152ba7cd47925dc2d71aa8956cbf01e

**Comment by archaeogeek** [comment]
@josegar74 awesome, that works perfectly, thanks!
